scan_timeout = 1000
command_timeout=1000 #(1s)

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = true

[character]
error_symbol = "[✗](#bf616a)"

[gcloud]
disabled = true
