name: Scan repo workflow
on: [push, pull_request]
jobs:
  my-job:
    name: ci scan job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Cyber Sierra Github CI Scan
        uses: cyber-sierra/cybersierra-scanning-workflow@v0.0.1
        env:
          CS_API_TOKEN: ${{ secrets.CS_API_TOKEN }}
          CS_SCAN_URL: "https://scanner-api.prod.eks.cybersierra.ai"
